### PR TITLE
google-cloud-monitoring v0.36.0 [noarch]

### PR DESCRIPTION
**Pull request by twoodwark**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

A new version is required in order to add new package `opencensus-ext-stackdriver`.  I am using 0.36.0 because this dependency is on <1.0.0, see: 
https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-stackdriver/setup.py#L42

where 
```
 'google-cloud-monitoring >= 0.30.0, < 1.0.0',
```

### CODE REVIEW

**Comment by twoodwark** [comment]
@conda-forge-admin, please rerender

**Comment by parthea** [comment]
Hi @twoodwark , 
Thanks for opening a PR! Are you interested to help with putting together a PR for version 2.0.0 also? Some of the links in this PR are broken as the repo has moved from https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/monitoring to https://github.com/googleapis/python-monitoring

**Comment by twoodwark** [comment]
@conda-forge-admin, please rerender

**Comment by twoodwark** [comment]
> Hi @twoodwark ,
> Thanks for opening a PR! Are you interested to help with putting together a PR for version 2.0.0 also? 

I am using other packages that still depend on <2.0.0 so that's not urgent for me. Perhaps later on.

> Some of the links in this PR are broken as the repo has moved from https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/monitoring to https://github.com/googleapis/python-monitoring

fixed

**Review by parthea — APPROVED** [review]

**Comment by parthea** [comment]
Thanks @twoodwark !

**Pull request merged**
